language: r
cache: packages
sudo: required
dist: trusty
env:
  global:
    - NOT_CRAN = true
apt_packages:
  - libnetcdf-dev
  - udunits-bin
  - libudunits2-dev
  - netcdf-bin
  - libproj-dev
  - libcurl4-gnutls-dev
  - libdap-dev
  - libgdal-dev
  - libgdal1h
  - libhdf5-7
  - libhdf5-dev
  - libhdf5-serial-dev
  - libgdal-dev
  - libgdal1-dev
r_packages:
  - rgdal